apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: pcifdedbr-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/rhtap-qe:596664e7fa66d15b1c4bf66fb3c85bbd08218a9a@sha256:4f7abb3626ff71e95c52b92691e5fe850653639b2ffb28a7aa96f04d769e881e
        name: container-image  
